app:
  name: myapp
  environment: development

mysql:
  driver: mysql
  host: localhost
  port: 3306
  username: myuser
  password: mypassword
  database: mydatabase
  parameters:
    collation: utf8mb4_unicode_ci
